### ISSUE TITLE
'NoneType' object has no attribute 'board'

### ISSUE THREAD

**Issue by orestisf1993** [marcusbuffett/command-line-chess#1]
Currently, the point difference is : 3
It's your move, what do you want to do? Type '?' for options. dxe7

Making move : dxe7
R N x K Q B x R 
p p x B p p p p 
x x p x x x x x 
x x x x x x x x 
x x x p x x x x 
x x x x x p x x 
p p p x x x p R 
R N B K Q B N x

AI thinking...
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    startGame(board, playerSide, opponentAI)
  File "main.py", line 113, in startGame
    move = ai.getBestMove()
  File "/tmp/command-line-chess-master/AI.py", line 123, in getBestMove
    moveTree = self.generateMoveTree()
  File "/tmp/command-line-chess-master/AI.py", line 78, in generateMoveTree
    self.populateNodeChildren(node)
  File "/tmp/command-line-chess-master/AI.py", line 91, in populateNodeChildren
    legalMoves = self.board.getAllMovesLegal(side)
  File "/tmp/command-line-chess-master/Board.py", line 397, in getAllMovesLegal
    if self.moveIsLegal(move) :
  File "/tmp/command-line-chess-master/Board.py", line 388, in moveIsLegal
    self.undoLastMove()
  File "/tmp/command-line-chess-master/Board.py", line 89, in undoLastMove
    self.pieces.remove(promotedPiece)
  File "/tmp/command-line-chess-master/Piece.py", line 37, in __eq__
    if self.board == other.board and self.side == other.side and self.position == other.position and self.__class__ == other.__class__:
AttributeError: 'NoneType' object has no attribute 'board'

**Comment by marcusbuffett** [comment]
I think this has been fixed (unfortunately I don't know how to reproduce the bug to check) so I'm closing it for now.
